apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-codecommit-static-website
  title: AWS (Codecommit) Static Website Template
  description: An example template for the scaffolder that creates a simple static website with S3, Codecommit and Codepipeline
  tags:
    - infrastructure
    - terraform
    - aws
    - s3
    - codecommit
    - codepipeline
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
        - env
      properties:
        name:
          title: Bucket
          type: string
          description: The name of the S3 bucket
        env:
          title: Environment
          type: string
          description: The environment to deploy the resources
          default: dev
          enum: [dev, staging, prod]

  steps:
    - id: fetch-content
      name: Fetch Content
      action: fetch:template
      input:
        targetPath: ./outputs/content
        url: ./content
        values:
          name: ${{ parameters.name }}

    - id: show-content-workspace
      name: Show content workspace files
      action: debug:log
      input:
        listWorkspace: true

    - id: fetch-devops
      name: Fetch Devops
      action: fetch:template
      input:
        targetPath: ./outputs/devops
        url: ./devops
        values:
          name: ${{ parameters.name }}

    - id: show-devops-workspace
      name: Show devops workspace files
      action: debug:log
      input:
        listWorkspace: true

    - id: publish-devops
      name: Create a pull request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=backstage-devops&owner=victoronl
        branchName: 'terraform/${{ parameters.name }}'
        title: Create ${{ parameters.name }} static website
        description: This is a pull request to create a new static website
        sourcePath: ./outputs/devops

    - id: register
      name: Register
      action: catalog:register
      input:
        catalogInfoUrl: 'https://raw.githubusercontent.com/victoronl/backstage-devops/terraform/${{ parameters.name }}/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/${{ parameters.name }}'
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
