apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-static-website
  title: AWS Static Website Template
  description: An example template for the scaffolder that creates a simple static website with S3, GitHub and Codepipeline
  tags:
    - infrastructure
    - terraform
    - aws
    - s3
    - github
    - codepipeline
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - bucket_name
        - env
      properties:
        bucket_name:
          title: Bucket
          type: string
          description: The name of the S3 bucket
        env:
          title: Environment
          type: string
          description: The environment to deploy the resources
          default: dev
          enum: [dev, staging, prod]
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-content
      name: Fetch Content
      action: fetch:template
      input:
        targetPath: ./outputs/content
        url: ./content
        values:
          name: ${{ parameters.bucket_name }}

    - id: show-content-workspace
      name: Show content workspace files
      action: debug:log
      input:
        listWorkspace: true

    - id: fetch-devops
      name: Fetch Devops
      action: fetch:template
      input:
        targetPath: ./outputs/devops
        url: ./devops
        values:
          name: ${{ parameters.bucket_name }}

    - id: show-devops-workspace
      name: Show devops workspace files
      action: debug:log
      input:
        listWorkspace: true

    - id: publish
      name: Publish
      action: publish:github
      input:
        defaultBranch: main
        sourcePath: ./outputs/content
        allowedHosts: ['github.com']
        description: This is ${{ parameters.bucket_name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: publish-devops
      name: Create a pull request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=backstage-devops&owner=victoronl
        branchName: 'terraform/${{ parameters.bucket_name }}'
        title: Create ${{ parameters.bucket_name }} static website
        description: This is a pull request to create a new static website
        sourcePath: ./outputs/devops

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
